[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Amund Desmarais <amunddesmarais64@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
lazy_static = "1.4.0"
array2d = "0.2.1"
num = "0.2.1"